package org.retropipes.dungeondiver7.loader.image.gameobject;

import java.net.URL;

import org.retropipes.diane.asset.image.DianeImageIndex;
import org.retropipes.diane.objectmodel.ObjectId;
import org.retropipes.dungeondiver7.locale.FileExtension;
import org.retropipes.dungeondiver7.locale.Strings;
import org.retropipes.dungeondiver7.locale.Untranslated;

public enum ObjectImageId implements DianeImageIndex, ObjectId {
	EMPTY, WALL, DARKNESS, BOUNDS, PARTY, NOTE, NOTHING, EASY_MONSTER, NORMAL_MONSTER, HARD_MONSTER, TILE, ARMOR_SHOP,
	BANK, HEALER, ITEM_SHOP, SPELL_SHOP, SURGE_SHOP, WEAPON_SHOP, STAIRS_DOWN, STAIRS_UP, GRASS, TREE, CUT_TREE, AXE,
	DIRT, WATER, DEEP_WATER, DEEPER_WATER, DEEPEST_WATER, BOOTS, FORCE_FIELD, ENERGY_SPHERE, PUSHABLE_BLOCK, ICE,
	SUNKEN_BLOCK, LAVA, SPRING, PIT, BOMB, BOMB_FUSE_1, BOMB_FUSE_2, BOMB_FUSE_3, BOMB_FUSE_4, BOOM, MISSILE_NORTH,
	MISSILE_EAST, MISSILE_WEST, MISSILE_SOUTH, COUNTERPOISON_AMULET, POISONOUS_AMULET, CREATION_WAND, DESTRUCTION_WAND,
	DISARM_TRAP_WAND, REMOTE_ACTION_WAND, LIGHT_WAND, FINISH_MAKING_WAND, ROTATION_WAND, DEATH_WAND, TELEPORT_SELF_WAND,
	TELEPORT_OBJECT_DOWN_WAND, TELEPORT_OBJECT_UP_WAND, TELEPORT_OBJECT_RANDOMLY_WAN, CLOCKWISE_ROTATE_SELF_TRAP,
	COUNTERCLOCKWISE_ROTATE_SELF_TRAP, CONFUSION_TRAP, DIZZY_TRAP, DRUNK_TRAP, U_TURN_TRAP, HURT_TRAP,
	VARIABLE_HURT_TRAP, HEAL_TRAP, VARIABLE_HEAL_TRAP, DRAIN_TRAP, VARIABLE_DRAIN_TRAP, SURGE_TRAP, VARIABLE_SURGE_TRAP,
	CLOCKWISE_ROTATE_LEVEL_TRAP, COUNTERCLOCKWISE_ROTATE_LEVEL_TRAP, WALL_TRAP, LIGHT_TRAP, DARKNESS_TRAP, WARP_TRAP,
	EXPLORE_ON_TRAP, EXPLORE_OFF_TRAP, LINE_OF_SIGHT_ON_TRAP, LINE_OF_SIGHT_OFF_TRAP, _NONE;

	@Override
	public String getName() {
		return Integer.toString(this.ordinal());
	}

	@Override
	public URL getURL() {
		return this.getClass().getResource(Strings.untranslated(Untranslated.OBJECT_IMAGE_LOAD_PATH) + this.getName()
				+ Strings.fileExtension(FileExtension.IMAGE));
	}
}
